name: jump_counter_app
description: A Flutter app to display live camera feed and jump counter results
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  http: ^1.1.0
  permission_handler: ^11.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

